### ISSUE TITLE
Configuring auth outside of firecloud: continuing to get authz_core:error AH01631

### ISSUE THREAD

**Issue by eap** [DataBiosphere/leonardo#202]
Using the docker image `broadinstitute/openidc-proxy:latest` I currently have it configured with docker-compose as below. My understanding is that this config should pass openid headers from the auth proxy to the Leo server as long as the user is valid. Even after going through the oauth consent flow, I'm getting the following error from the auth proxy when attempting to access the leonardo resources.

Various sources on the intertubes indicate 'AH01631' could have something to do with LDAP server config. Is there any way to entirely disable LDAP based auth in this image?

```
proxy_1     | [Fri Feb 16 18:09:12.192220 2018] [authz_core:error] [pid 42:tid 140343341176576] [client 104.132.1.86:47586] AH01631: user 114308269537946046304: authorization failure for "/api/cluster/kumo-forseti-workspace/evanclustertrytenbillion": , referer: https://~~~DOMAIN~~~/
```

Docker compose for proxy:
```
proxy:
    image: broadinstitute/openidc-proxy:latest
    ports: ["80:80", "443:443", "127.0.0.1:8888:8888"]
    links: ["app:app"]
    volumes:
      - /app/server.crt:/etc/ssl/certs/server.crt:ro
      - /app/server.key:/etc/ssl/private/server.key:ro
      - /app/ca-bundle.crt:/etc/ssl/certs/ca-bundle.crt:ro
      - /app/site.conf:/etc/apache2/sites-available/site.conf
    # logging: ~~not configured, send to stdout~~
    environment:
      CALLBACK_URI: https://~~my-test-domain-name~~/oauth2callback
      LOG_LEVEL: warn
      SERVER_NAME: ~~my-test-domain-name~~
      AUTH_REQUIRE2: Require valid-user
      AUTH_TYPE2: AuthType oauth20
      REMOTE_USER_CLAIM: sub
      ENABLE_STACKDRIVER: 'yes'
      FILTER2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript application/x-javascript
    restart: always
```
